version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Ganesh495@cmrit
      MYSQL_DATABASE: portfolio_db
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
