version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Ganesh495@cmrit
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ganesh495@cmrit
    ports:
      - "3306:3306"
